<?php

define('_HTML_PATH',               dirname(__FILE__).'/');
define('_WWW_PATH',                dirname(_HTML_PATH).'/');
define('_DATA_PATH',               _WWW_PATH.'data/');

define('_CSS_PATH',                _DATA_PATH.'css/');
define('_IMAGES_LAYOUT_PATH',      _DATA_PATH.'images/layout/');
define('_ALUBUM_ENG_PATH',         _DATA_PATH.'images/alubum/eng/');
define('_ALUBUM_JPN_PATH',         _DATA_PATH.'images/alubum/jpn/');
define('_JS_PATH',                 _DATA_PATH.'js/');
define('_CLASS_PATH',              _DATA_PATH.'class/');
define('_BOOTSTRAP_PATH',          _DATA_PATH.'bootstrap/');
define('_SMARTY_PATH',             _DATA_PATH.'Smarty/');

define('_FT_HTML_PATH',            '/original/html/');
define('_FT_WWW_PATH',             dirname(_FT_HTML_PATH).'/');
define('_FT_DATA_PATH',            _FT_WWW_PATH.'data/');

define('_FT_CSS_PATH',             _FT_DATA_PATH.'css/');
define('_FT_IMAGES_LAYOUT_PATH',   _FT_DATA_PATH.'images/layout/');
define('_FT_ALUBUM_ENG_PATH',      _FT_DATA_PATH.'images/alubum/eng/');
define('_FT_ALUBUM_JPN_PATH',      _FT_DATA_PATH.'images/alubum/jpn/');
define('_FT_JS_PATH',              _FT_DATA_PATH.'js/');
define('_FT_BOOTSTRAP_PATH',       _FT_DATA_PATH.'bootstrap/');