<?php

const SSMARTY = '/vagrant/demo_site/original/data/Smarty/';
const SDATA = '/vagrant/demo_site/original/data/';
const SHTML = '/vagrant/demo_site/original/html/';
const PCSS = 'http://demo_site/original/data/css/';
const PJS = 'http://demo_site/original/data/js/';
const PIMAGES = 'http://demo_site/original/data/images/';
const BOOTSTRAP = 'http://demo_site/original/data/bootstrap/';
const PHTML = 'http://demo_site/original/html/';

define('_HTML_JPN_PATH',                   _HTML_PATH.'jpn/');

define('_HTML_JPN_REGISTER_PATH',          _HTML_JPN_PATH.'register/');
define('_HTML_JPN_MEMBERPAGE_PATH',        _HTML_JPN_PATH.'memberpage/');
define('_HTML_JPN_FORGOTTEN_PATH',         _HTML_JPN_PATH.'forgotten/');
define('_HTML_JPN_ABOUT_PATH',             _HTML_JPN_PATH.'about/');

define('_TEMPLATES_JPN_PATH',              _SMARTY_PATH.'templates/jpn/');

define('_TEMPLATES_JPN_REGISTER_PATH',     _TEMPLATES_JPN_PATH.'register/');
define('_TEMPLATES_JPN_MEMBERPAGE_PATH',   _TEMPLATES_JPN_PATH.'memberpage/');
define('_TEMPLATES_JPN_FORGOTTEN_PATH',    _TEMPLATES_JPN_PATH.'forgotten/');
define('_TEMPLATES_JPN_ABOUT_PATH',        _TEMPLATES_JPN_PATH.'about/');

define('_FT_HTML_JPN_PATH',                   _FT_HTML_PATH.'jpn/');

define('_FT_HTML_JPN_REGISTER_PATH',          _FT_HTML_JPN_PATH.'register/');
define('_FT_HTML_JPN_MEMBERPAGE_PATH',        _FT_HTML_JPN_PATH.'memberpage/');
define('_FT_HTML_JPN_FORGOTTEN_PATH',         _FT_HTML_JPN_PATH.'forgotten/');
define('_FT_HTML_JPN_ABOUT_PATH',             _FT_HTML_JPN_PATH.'about/');